/**
 * Generates `src/ui/icons.rs` from the reference app's lucide-react icon set.
 *
 * Usage:
 *   node scripts/gen-icons.mjs <path-to-lucide-react/dist/esm/icons>
 *
 * The generated file renders the exact SVG markup lucide-react 1.x emits
 * (same attributes and children) so icon geometry matches the React reference.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const esmDir = process.argv[2];
const iconDir = path.join(process.argv[2], "icons");
if (!iconDir || !fs.existsSync(iconDir)) {
  console.error("usage: node scripts/gen-icons.mjs <lucide-react/dist/esm/icons>");
  process.exit(2);
}

const NAMES = [
  "Activity",
  "AlertTriangle",
  "ArrowDown",
  "ArrowRight",
  "ArrowUp",
  "ArrowUpDown",
  "BarChart3",
  "CalendarDays",
  "Check",
  "CheckCircle2",
  "ClipboardPaste",
  "Clock",
  "Columns2",
  "Copy",
  "Database",
  "Download",
  "Eraser",
  "ExternalLink",
  "FilePlus",
  "FileText",
  "Filter",
  "Flame",
  "Globe",
  "Info",
  "Lightbulb",
  "Moon",
  "Network",
  "Plus",
  "RefreshCw",
  "RotateCcw",
  "Rows",
  "Search",
  "ShieldAlert",
  "Sun",
  "Terminal",
  "Timer",
  "Upload",
  "User",
  "UserCheck",
  "Users",
  "X",
];

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

// Build export-name -> icon file map from the library index.
const index = fs.readFileSync(path.join(esmDir, "lucide-react.mjs"), "utf8");
const fileFor = new Map();
for (const m of index.matchAll(/export \{([^}]*)\} from '\.\/icons\/([^']+)'/g)) {
  const names = m[1].split(",").map((x) => x.split(" as ").pop().trim());
  for (const n of names) fileFor.set(n, path.join(iconDir, m[2]));
}

async function loadIcon(importName) {
  const file = fileFor.get(importName) ?? path.join(iconDir, `${kebab(importName)}.mjs`);
  if (!fs.existsSync(file)) throw new Error(`missing icon file for ${importName}`);
  const mod = await import(pathToFileURL(file).href);
  const canonical = kebab(mod.default.displayName ?? importName);
  return { node: mod.__iconNode, canonical };
}

const ATTR_ORDER = [
  "d",
  "cx",
  "cy",
  "r",
  "x",
  "y",
  "width",
  "height",
  "rx",
  "ry",
  "points",
  "x1",
  "y1",
  "x2",
  "y2",
  "transform",
];

const esc = (s) => s.replace(/&/g, "&amp;").replace(/"/g, "&quot;");

const entries = [];
const aliases = [];
for (const name of NAMES) {
  const { node, canonical } = await loadIcon(name);
  const alias = kebab(name);
  if (alias !== canonical) aliases.push([alias, canonical]);
  const children = node
    .map(([tag, attrs]) => {
      const parts = [];
      for (const a of ATTR_ORDER) {
        if (attrs[a] === undefined) continue;
        const svgName = a === "transform" ? "transform" : a;
        parts.push(`${svgName}="${esc(String(attrs[a]))}"`);
      }
      return `<${tag} ${parts.join(" ")}/>`;
    })
    .join("");
  entries.push({ key: canonical, children });
  console.log(`ok ${canonical}${alias !== canonical ? ` (alias ${alias})` : ""}`);
}

const rust = `// @generated by scripts/gen-icons.mjs — do not edit by hand.
// Source: lucide-react v1.39.0 (ISC) via the reference app's node_modules.
#![allow(dead_code)]

use dioxus::prelude::*;

/// Resolve a lucide-react import name to its canonical icon name.
pub fn canonical(name: &str) -> &str {
    match name {
${aliases.map(([a, c]) => `        ${JSON.stringify(a)} => ${JSON.stringify(c)},`).join("\n")}
        _ => name,
    }
}

/// Inner SVG markup for a lucide icon (children only).
pub fn svg_inner(name: &str) -> &'static str {
    match name {
${entries.map((e) => `        ${JSON.stringify(e.key)} => r#"${e.children}"#,`).join("\n")}
        _ => "",
    }
}

#[component]
pub fn Icon(name: String, class: String) -> Element {
    let canonical_name = canonical(&name).to_string();
    rsx! {
        svg {
            xmlns: "http://www.w3.org/2000/svg",
            width: "24",
            height: "24",
            view_box: "0 0 24 24",
            fill: "none",
            stroke: "currentColor",
            stroke_width: "2",
            stroke_linecap: "round",
            stroke_linejoin: "round",
            class: "lucide lucide-{canonical_name} {class}",
            "aria-hidden": "true",
            dangerous_inner_html: svg_inner(&canonical_name),
        }
    }
}
`;

fs.writeFileSync(path.join(__dirname, "..", "src", "ui", "icons.rs"), rust);
console.log(`wrote src/ui/icons.rs (${entries.length} icons)`);
