//! App icons via `fastframe_icons`.
//!
//! The 18 icons ZapFast and Spotifast share come from the crate's bundled
//! Lucide set (`lucide "name"`); every other icon ships as this app's own
//! SVG in `assets/icons/`, generated by `scripts/gen-icons.mjs` from the
//! reference app's lucide-react set. All SVGs are 24 px white outlines, so
//! egui's tint is the colour on screen.

use egui::{Color32, Image};
use fastframe_icons::icons;

icons! {
    /// Every icon the PM2 Log Analyzer interface draws.
    pub enum Icon {
        prefix: "pm2-icon-",
        directory: "../../assets/icons/",
        Activity => "activity",
        AlertTriangle => "alert-triangle",
        ArrowDown => "arrow-down",
        ArrowLeft => lucide "arrow-left",
        ArrowRight => "arrow-right",
        ArrowUp => "arrow-up",
        ArrowUpDown => "arrow-up-down",
        CalendarDays => "calendar-days",
        ChartColumn => "chart-column",
        Check => lucide "check",
        CircleCheck => lucide "circle-check",
        ChevronDown => lucide "chevron-down",
        ChevronLeft => lucide "chevron-left",
        ChevronRight => lucide "chevron-right",
        ChevronUp => lucide "chevron-up",
        ClipboardPaste => "clipboard-paste",
        Clock => lucide "clock",
        Columns2 => "columns2",
        Copy => lucide "copy",
        Database => "database",
        Download => "download",
        Eraser => "eraser",
        ExternalLink => lucide "external-link",
        FilePlus => "file-plus",
        FileText => "file-text",
        Flame => "flame",
        FolderOpen => "folder-open",
        Funnel => "funnel",
        Globe => "globe",
        Info => lucide "info",
        Lightbulb => "lightbulb",
        Moon => lucide "moon",
        Network => "network",
        Plus => lucide "plus",
        RefreshCw => lucide "refresh-cw",
        RotateCcw => "rotate-ccw",
        Rows2 => "rows2",
        Search => lucide "search",
        ShieldAlert => "shield-alert",
        Sun => lucide "sun",
        Terminal => "terminal",
        Timer => "timer",
        Upload => "upload",
        User => lucide "user",
        UserCheck => "user-check",
        Users => lucide "users",
        X => lucide "x",
    }
}

/// Installs the never-forget bytes loader (survives `reduce_texture_memory`).
pub fn install_icons(ctx: &egui::Context) {
    fastframe_icons::install::<Icon>(ctx);
}

/// String-name shim kept for the view modules, which render icons by their
/// reference-app Lucide names.
pub fn render_icon(name: &str, color: Color32, size: f32) -> Image<'static> {
    from_name(name).image(color, size)
}

fn from_name(name: &str) -> Icon {
    match name {
        "activity" => Icon::Activity,
        "triangle-alert" | "alert-triangle" => Icon::AlertTriangle,
        "arrow-down" => Icon::ArrowDown,
        "arrow-left" => Icon::ArrowLeft,
        "arrow-right" => Icon::ArrowRight,
        "arrow-up" => Icon::ArrowUp,
        "arrow-up-down" => Icon::ArrowUpDown,
        "calendar-days" => Icon::CalendarDays,
        "chart-column" | "bar-chart3" => Icon::ChartColumn,
        "check" => Icon::Check,
        "circle-check" | "check-circle2" => Icon::CircleCheck,
        "chevron-down" => Icon::ChevronDown,
        "chevron-left" => Icon::ChevronLeft,
        "chevron-right" => Icon::ChevronRight,
        "chevron-up" => Icon::ChevronUp,
        "clipboard-paste" => Icon::ClipboardPaste,
        "clock" => Icon::Clock,
        "columns2" => Icon::Columns2,
        "copy" => Icon::Copy,
        "database" => Icon::Database,
        "download" => Icon::Download,
        "eraser" => Icon::Eraser,
        "external-link" => Icon::ExternalLink,
        "file-plus" => Icon::FilePlus,
        "file-text" => Icon::FileText,
        "flame" => Icon::Flame,
        "folder-open" => Icon::FolderOpen,
        "funnel" | "filter" => Icon::Funnel,
        "globe" => Icon::Globe,
        "info" => Icon::Info,
        "lightbulb" => Icon::Lightbulb,
        "moon" => Icon::Moon,
        "network" => Icon::Network,
        "plus" => Icon::Plus,
        "refresh-cw" => Icon::RefreshCw,
        "rotate-ccw" => Icon::RotateCcw,
        "rows2" | "rows" => Icon::Rows2,
        "search" => Icon::Search,
        "shield-alert" => Icon::ShieldAlert,
        "sun" => Icon::Sun,
        "terminal" => Icon::Terminal,
        "timer" => Icon::Timer,
        "upload" => Icon::Upload,
        "user" => Icon::User,
        "user-check" => Icon::UserCheck,
        "users" => Icon::Users,
        "x" => Icon::X,
        _ => Icon::Info,
    }
}
